apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller
spec:
  selector:
    matchLabels:
      app: caller
  replicas: 1
  template:
    metadata:
      labels:
        app: caller
    spec:
      containers:
        - name: caller
          image: quay.io/min_ji_gz_ibm/cloudnative/squad5
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          imagePullPolicy: Always
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
